apiVersion: v1
kind: Service
metadata:
  name: bradenp-ged-prod-redis-service
  labels:
    username: bradenp
    env: prod
spec:
  type: ClusterIP
  # clusterIP: 10.104.165.3 # Remove comment and change IP accordingly to force an IP for the redis service
  selector:
    username: bradenp
    env: prod
    app: bradenp-ged-prod-redis
  ports:
  - name: bradenp-ged-prod-redis
    port: 6379
    targetPort: 6379