---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bradenp-ged-prod-redis-pvc
  labels:
    username: bradenp
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi