---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bradenp-ged-prod-worker-deployment
  labels:
    username: bradenp
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      username: bradenp
      env: prod
  template:
    metadata:
      labels:
        username: bradenp
        env: prod
        app: bradenp-prod-worker
    spec:
      containers:
        - name: prod
          imagePullPolicy: Always
          image: bradenpecora/global-energy-data-app:1.0.2
          args: ["worker.py"]
          env:
          - name: REDIS_IP
            value: "10.96.244.146" # Change this to the Cluster IP of the redis service
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: WORKER_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
